name: "Transcode Killer"
guid: "a0444c3b-fe1c-4258-9e0f-a139fc093949"
version: "1"
targetAbi: "10.8.1.0"
framework: "net6.0"
owner: "crobibero"
overview: "Kills transcoded streams."
description: >
  Kills transcoded streams.

category: "General"
artifacts:
  - "Jellyfin.Plugin.TranscodeKiller.dll"
changelog: |-
